=== aamandapalomo/XSDXMLOntologyBuilder/target/test-classes/Testing_minimum_requirements.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns="edu.upc.dmag" targetNamespace="edu.upc.dmag"
           elementFormDefault="qualified">

    <xs:complexType name="Actor">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="arbitrary_value" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Content">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="arbitrary_value" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Requirement">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="actor" type="ns:Actor"/>
            <xs:element name="related_content" type="ns:Content"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="requirement" type="ns:Requirement" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== aamandapalomo/XSDXMLOntologyBuilder/target/test-classes/minimum_requirements_example1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<ns:root xmlns:ns="edu.upc.dmag" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="edu.upc.dmag Testing_minimum_requirements.xsd">
    <ns:requirement>
        <ns:name>Requirement test 1</ns:name>
        <ns:actor>
            <ns:name>actor test 1</ns:name>
            <ns:arbitrary_value>1</ns:arbitrary_value>
        </ns:actor>
        <ns:related_content>
            <ns:name>content 1</ns:name>
            <ns:arbitrary_value>1</ns:arbitrary_value>
        </ns:related_content>
    </ns:requirement>

    <ns:requirement>
        <ns:name>Requirement test 1 bis</ns:name>
        <ns:actor>
            <ns:name>actor test 1</ns:name>
            <ns:arbitrary_value>1</ns:arbitrary_value>
        </ns:actor>
        <ns:related_content>
            <ns:name>content 2</ns:name>
            <ns:arbitrary_value>2</ns:arbitrary_value>
        </ns:related_content>
    </ns:requirement>

    <ns:requirement>
        <ns:name>Requirement test 2</ns:name>
        <ns:actor>
            <ns:name>actor test 2</ns:name>
            <ns:arbitrary_value>2</ns:arbitrary_value>
        </ns:actor>
        <ns:related_content>
            <ns:name>content 1</ns:name>
            <ns:arbitrary_value>1</ns:arbitrary_value>
        </ns:related_content>
    </ns:requirement>
</ns:root>
