=== aamandapalomo/XSDXMLOntologyBuilder/target/test-classes/TestingSequence.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns="edu.upc.dmag" targetNamespace="edu.upc.dmag"
           elementFormDefault="qualified">

    <xs:complexType name="sequenceEntryType">
        <xs:sequence>
            <xs:element name="element_a" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="rootEntryType">
        <xs:sequence>
            <xs:element name="sequenceEntry" type="ns:sequenceEntryType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>



    <xs:element name="root">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="entry" type="ns:rootEntryType" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== aamandapalomo/XSDXMLOntologyBuilder/target/test-classes/sequence_exampleWithDuplicateEntry.xml
<?xml version="1.0" encoding="UTF-8" ?>
<ns:root xmlns:ns="edu.upc.dmag" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="edu.upc.dmag TestingSequence.xsd">
    <ns:entry>
        <ns:sequenceEntry>
            <ns:element_a>test_a1</ns:element_a>
        </ns:sequenceEntry>
        <ns:sequenceEntry>
            <ns:element_a>test_b1</ns:element_a>
        </ns:sequenceEntry>
    </ns:entry>

    <ns:entry>
        <ns:sequenceEntry>
            <ns:element_a>test_a2</ns:element_a>
        </ns:sequenceEntry>
        <ns:sequenceEntry>
            <ns:element_a>test_b1</ns:element_a>
        </ns:sequenceEntry>
    </ns:entry>
</ns:root>
